### ISSUE TITLE
Authorize Password and Client Credentials not working correctly

### ISSUE THREAD

**Issue by jenschude** [advanced-rest-client/oauth-authorization#1]
When using API console 4 I'm getting errors for accessing properties accessTokenUrl at undefined object.

In comparison to 

```javascript
  // Authorize the user in the browser flow.
  _authorizeCode: function(settings) {
    this._settings = settings;
```
the _authorizeClientCredential and is _authorizePassword method are not setting the _settings property upfront and directly try to access the accessTokenUrl which results in the described behavior.

```javascript
  _authorizePassword: function(settings) {
    var url = this._settings.accessTokenUrl;
```

```
  _authorizeClientCredential: function(settings) {
    var url = this._settings.accessTokenUrl;
```

**Comment by jarrodek** [comment]
Sorry, I forgot to close this issue after it was fixed. It was fixed few months ago.
